// ─── Signals ──────────────────────────────────────────────────────────────────
import { useState, useEffect, useCallback, useRef } from "react";
import { NavLink, useSearchParams } from "react-router-dom";
import { C } from "../utils/constants.jsx";
import { Card, SectionTitle, Grid, Btn, Sel, FG, Pill, useMobile } from "../shared/Shared.jsx";
import { fp, f1 } from "../utils/utils.js";
import { CandleChart1, ConfRing, SigCard } from "../components/Charts.jsx";
import { PAIRS, FOREX_PAIRS, TFS } from "../components/Charts.jsx";
import { ChartWrap, Badge, ErrBox,Stat } from "../shared/Shared.jsx";
import { WS_BASE } from "../api/Api.jsx";
import { useLiveSocket } from "../hooks/useLiveSocket.js";
import { useSyncedMarketPrefs } from "../utils/marketPrefs.js";

const SIGNALS_WS_URL = `${WS_BASE}/ws/signals`;

export default function Signals({ api }) {
  const mobile = useMobile();
  const [searchParams] = useSearchParams();
  const [lastCopied, setLastCopied] = useState(null); // { pair, direction } — shown as a "view in Copy Trading" banner
  const { prefs: marketPrefs, setTimeframe: syncTimeframe } = useSyncedMarketPrefs(api, true);
  const [pair,    setPair]    = useState(marketPrefs.watchlist[0] || "EURUSD");
  const [tf,      setTfRaw]   = useState(marketPrefs.timeframe || "H1");
  const setTf = useCallback((v) => { setTfRaw(v); syncTimeframe(v); }, [syncTimeframe]);
  const [sigs,    setSigs]    = useState([]);
  const [sel,     setSel]     = useState(null);
  const [bars,    setBars]    = useState([]);
  const [busy,    setBusy]    = useState(false);
  const [bulkP,   setBulkP]   = useState(marketPrefs.watchlist.length ? marketPrefs.watchlist : ["EURUSD","GBPUSD","USDJPY","GBPJPY","USDCHF","AUDUSD","USDCAD","NZDUSD"]);
  const [bulkTf,  setBulkTf]  = useState(["H1","H4"]);
  const [minConf, setMinConf] = useState(0);
  const [dirF,    setDirF]    = useState("ALL");
  const [subTab,  setSubTab]  = useState("gen"); // gen | history
  const [pendingReview, setPendingReview] = useState([]);
  const [pendingBusy, setPendingBusy] = useState(null); // signal id currently being approved/rejected
  const [hPair,   setHPair]   = useState("EURUSD");
  const [hTf,     setHTf]     = useState("H1");
  const [hPer,    setHPer]    = useState("1M");
  const [hData,   setHData]   = useState(null);
  const [hBusy,   setHBusy]   = useState(false);
  const [btPair,  setBtPair]  = useState("EURUSD");
  const [btTf,    setBtTf]    = useState("H1");
  const [btBars,  setBtBars]  = useState(1000);
  const [btData,  setBtData]  = useState(null);
  const [btBusy,  setBtBusy]  = useState(false);
  const [btErr,   setBtErr]   = useState("");
  // Read-only viewer for a clicked History or Backtest item — deliberately
  // separate from `sel`/Detail above: those entries aren't real persisted
  // signals (no id), so they can't be copied/approved like a live one, and
  // reusing that state would also fight with the gen tab's own live-candle
  // websocket subscription. { pair, timeframe, direction, entry, sl, tp,
  // confidence, label, kind: 'history'|'backtest' }
  const [resSel,  setResSel]  = useState(null);
  const [resBars, setResBars] = useState([]);
  useEffect(() => {
    if (!resSel) return;
    setResBars([]);
    api.get(`/prices/chart?pair=${resSel.pair}&timeframe=${resSel.timeframe}&candles=80`)
      .then(d => setResBars(d.candles || [])).catch(() => {});
  }, [resSel, api]);
  const [newIds,  setNewIds]  = useState(new Set());
  const [copiedIds, setCopiedIds] = useState(new Set());
  const [copyBusy,  setCopyBusy]  = useState(null);
  const [copyErr,   setCopyErr]   = useState("");
  const [executeLive, setExecuteLive] = useState(false);
  const [bridgeReady, setBridgeReady] = useState(false);
  const [usage, setUsage] = useState(null);
  const [genErr, setGenErr] = useState("");

  const loadUsage = useCallback(() => {
    api.get("/account/usage").then(setUsage).catch(() => {});
  }, [api]);

  useEffect(() => {
    api.get("/bridge/status").then((d) => setBridgeReady(!!d.has_token)).catch(() => {});
    loadUsage();
  }, [api, loadUsage]);

  // (timeframe sync now handled by setTf → useSyncedMarketPrefs, no separate effect needed)

  const copySignal = async (sigId, sigObj) => {
    setCopyBusy(sigId); setCopyErr(""); setLastCopied(null);
    try {
      const res = await api.post(`/signals/${sigId}/copy`, { lot_size: 0.02, risk_pct: 2, execute_live: executeLive && bridgeReady });
      setCopiedIds((prev) => new Set(prev).add(sigId));
      setLastCopied({ pair: res.pair || sigObj?.pair, direction: res.direction || sigObj?.direction, mode: res.execution_mode });
      loadUsage();
    } catch (e) {
      setCopyErr(e.message || "Could not copy this signal");
    } finally {
      setCopyBusy(null);
    }
  };

  // Live signal feed — every signal generated by anyone (manual or the AI auto-rotation)
  // streams in here instantly, no polling required.
  const onSignalMsg = useCallback((d) => {
    if (d?.type === "new_signal" && d.data) {
      const sig = d.data;
      setSigs((prev) => {
        if (prev.some((s) => s.id === sig.id)) return prev;
        return [sig, ...prev].slice(0, 30);
      });
      setNewIds((prev) => new Set(prev).add(sig.id));
      setTimeout(() => setNewIds((prev) => { const n = new Set(prev); n.delete(sig.id); return n; }), 8000);
    } else if (d?.type === "signal_closed" && d.data) {
      const { id, result, pnl_pips, close_price } = d.data;
      setSigs((prev) => prev.map((s) => s.id === id ? { ...s, status: "closed", result, pnl_pips, close_price } : s));
      setSel((prev) => prev && prev.id === id ? { ...prev, status: "closed", result, pnl_pips, close_price } : prev);
    }
  }, []);
  const liveStatus = useLiveSocket(SIGNALS_WS_URL, onSignalMsg);

  // Fetch chart when signal selected
  const loadSelChartRef = useRef(null);
  const loadSelChart = useCallback(() => {
    if (!sel) return;
    api.get(`/prices/chart?pair=${sel.pair}&timeframe=${sel.timeframe}&candles=80`)
      .then(d => setBars(d.candles || [])).catch(() => {});
  }, [sel, api]);
  loadSelChartRef.current = loadSelChart;

  useEffect(() => {
    setBars([]); // clear the previous signal's candles immediately on switch
    loadSelChart();
  }, [sel, loadSelChart]);

  // ── Live candle stream for the selected signal's pair/timeframe — the detail
  // chart used to be a one-shot REST fetch with no live updates at all. ──
  const [liveCandle, setLiveCandle] = useState(null);
  const selCandleWsUrl = sel ? `${WS_BASE}/ws/candles?pair=${sel.pair}&timeframe=${sel.timeframe}` : null;
  const onSelCandleMsg = useCallback((d) => {
    if (d?.type === "candle_update" && d.candle) {
      setLiveCandle(d.candle);
    } else if (d?.type === "candle_closed") {
      loadSelChartRef.current && loadSelChartRef.current();
    }
  }, []);
  const selCandleStatus = useLiveSocket(selCandleWsUrl, onSelCandleMsg);
  useEffect(() => { setLiveCandle(null); }, [sel?.id]);

  const [delayInfo, setDelayInfo] = useState(null); // { plan_delay_minutes, realtime_signals_locked }

  // Load latest on mount; if Dashboard linked here with ?id=123, open that exact signal.
  useEffect(() => {
    api.get("/signals/latest?limit=20").then(d => {
      setSigs(d.signals || []);
      setDelayInfo({ delay: d.plan_delay_minutes || 0, locked: d.realtime_signals_locked || 0 });
      const wantId = searchParams.get("id");
      if (wantId) {
        const found = (d.signals || []).find(s => String(s.id) === wantId);
        if (found) { setSel(found); return; }
        api.get(`/signals/${wantId}`).then(s => setSel(s)).catch(() => {});
      }
    }).catch(() => {});
  }, []);

  const loadPendingReview = useCallback(() => {
    api.get("/signals/pending-review").then(d => setPendingReview(d.signals || [])).catch(() => {});
  }, [api]);

  useEffect(() => { loadPendingReview(); }, [loadPendingReview]);

  const approveSignal = async (id) => {
    setPendingBusy(id);
    try {
      await api.post(`/signals/${id}/approve`);
      setPendingReview((p) => p.filter((s) => s.id !== id));
    } catch (e) { alert(e.message); }
    finally { setPendingBusy(null); }
  };
  const rejectSignal = async (id) => {
    setPendingBusy(id);
    try {
      await api.post(`/signals/${id}/reject`);
      setPendingReview((p) => p.filter((s) => s.id !== id));
    } catch (e) { alert(e.message); }
    finally { setPendingBusy(null); }
  };

  const generate = async () => {
    setBusy(true); setGenErr("");
    try {
      const s = await api.post("/signals/generate", { pair, timeframe: tf });
      setSigs(p => [s, ...p.slice(0, 19)]);
      setSel(s);
      loadUsage();
      if (s.needs_approval) loadPendingReview();
    } catch (e) { setGenErr(e.message); }
    finally { setBusy(false); }
  };

  const bulk = async () => {
    setBusy(true); setGenErr("");
    try {
      const d = await api.post("/signals/bulk", { pairs: bulkP, timeframes: bulkTf, min_confidence: minConf, direction_filter: dirF });
      const list = d.signals || [];
      setSigs(list);
      if (list.length) setSel(list[0]);
      loadUsage();
      if (d.needs_approval) loadPendingReview();
    } catch (e) { setGenErr(e.message); }
    finally { setBusy(false); }
  };

  const loadHistory = async () => {
    setHBusy(true); setResSel(null);
    try { const d = await api.get(`/signals/history?pair=${hPair}&timeframe=${hTf}&period=${hPer}`); setHData(d); }
    catch (e) { alert(e.message); }
    finally { setHBusy(false); }
  };

  const loadBacktest = async () => {
    setBtBusy(true); setBtErr(""); setBtData(null); setResSel(null);
    try { const d = await api.get(`/signals/backtest?pair=${btPair}&timeframe=${btTf}&bars=${btBars}`); setBtData(d); }
    catch (e) { setBtErr(e.message); }
    finally { setBtBusy(false); }
  };

  // Signal detail panel
  // Compact read-only result panel for a clicked History/Backtest item — same
  // spirit as Detail below (metrics + chart) but no Copy/approve actions,
  // since these aren't executable live signals.
  const ResultDetail = () => {
    if (!resSel) return null;
    const buy = resSel.direction === "BUY";
    const dc = buy ? C.green : C.red;
    return (
      <Card style={{ marginTop: 12, border: `1px solid ${C.border}` }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{ fontSize: 20, fontWeight: 800 }}>{resSel.pair}</div>
            <Badge col={dc}>{buy ? "▲ BUY" : "▼ SELL"}</Badge>
            <span style={{ fontSize: 11, color: C.muted }}>{resSel.label}</span>
          </div>
          <button onClick={() => setResSel(null)} style={{ background: "none", border: "none", color: C.muted, fontSize: 18, cursor: "pointer" }}>×</button>
        </div>
        <Grid cols="repeat(4,minmax(0,1fr))" mobileCols="1fr 1fr" gap={10} style={{ marginBottom: 14 }}>
          {[["ENTRY", fp(resSel.entry), C.text], ["STOP LOSS", fp(resSel.sl), C.red],
            ["TAKE PROFIT", fp(resSel.tp), C.green], ["CONFIDENCE", `${resSel.confidence}%`, C.gold]].map(([l, v, c]) => (
            <div key={l} style={{ background: `linear-gradient(160deg, ${c}12, ${C.surf2})`, border: `1px solid ${C.border}`,
                                    borderTop: `2px solid ${c}`, borderRadius: 10, padding: "10px 8px", textAlign: "center" }}>
              <div style={{ fontSize: 9, color: C.muted, marginBottom: 4, fontWeight: 600 }}>{l}</div>
              <div style={{ fontSize: 14, fontWeight: 800, color: c, fontFamily: "monospace" }}>{v}</div>
            </div>
          ))}
        </Grid>
        <ChartWrap label={`Chart around ${resSel.label}`}>
          <CandleChart1
            bars={resBars}
            resetKey={`res_${resSel.pair}_${resSel.timeframe}_${resSel.entry}`}
            pair={resSel.pair}
            timeframe={resSel.timeframe}
            api={api}
            height={mobile ? 260 : 380}
            entry={resSel.entry} sl={resSel.sl} tp={resSel.tp}
            indicators={marketPrefs.indicators}
            enableDrawing={false}
          />
        </ChartWrap>
      </Card>
    );
  };

  const Detail = ({ s }) => {
    if (!s) return (
      <Card style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: 300 }}>
        <span style={{ color: C.muted, fontSize: 13 }}>Select or generate a signal to view details</span>
      </Card>
    );
    const buy = s.direction === "BUY";
    const dc  = buy ? C.green : C.red;
    return (
      <Card style={{
        background: `linear-gradient(180deg, ${C.surf2} 0%, ${C.surf} 140px)`,
        border: `1px solid ${C.border}`,
      }}>
        {/* Header */}
        <div style={{
          display: "flex", justifyContent: "space-between", alignItems: "flex-start",
          marginBottom: 16, paddingBottom: 14, borderBottom: `1px solid ${C.border}`,
        }}>
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
              <div style={{ fontSize: 28, fontWeight: 800, letterSpacing: 0.2 }}>{s.pair}</div>
              <Badge col={dc}>{buy ? "▲ BUY" : "▼ SELL"}</Badge>
            </div>
            <div style={{ fontSize: 11, color: C.muted, marginTop: 5, display: "flex", alignItems: "center", gap: 6 }}>
              <span style={{ fontWeight: 700, color: C.gold }}>{s.timeframe}</span>
              <span style={{ opacity: 0.4 }}>·</span>
              <span>{s.entry_time}</span>
            </div>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
            {s.approval_status === "pending_review" ? (
              <Badge col={C.gold}>⏳ Awaiting your approval</Badge>
            ) : s.status === "closed" ? (
              <Badge col={s.result === "win" ? C.green : s.result === "loss" ? C.red : C.muted}>
                {(s.result || "").toUpperCase()} · {s.pnl_pips >= 0 ? "+" : ""}{f1(s.pnl_pips)} pips
              </Badge>
            ) : copiedIds.has(s.id) ? (
              <Badge col={C.green}>✓ Copied</Badge>
            ) : usage && usage.limits.copies_per_day != null && usage.usage.copies_today >= usage.limits.copies_per_day ? (
              <NavLink to="/billing" style={{ textDecoration: "none" }}>
                <Btn col={C.gold}>Daily copy limit reached — Upgrade</Btn>
              </NavLink>
            ) : (
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                {bridgeReady && (
                  <label style={{ display: "flex", alignItems: "center", gap: 5, fontSize: 10, color: C.muted, cursor: "pointer" }}>
                    <input type="checkbox" checked={executeLive} onChange={(e) => setExecuteLive(e.target.checked)} />
                    Execute live (MT5)
                  </label>
                )}
                <Btn col={C.gold} onClick={() => copySignal(s.id, s)} disabled={copyBusy === s.id}>
                  {copyBusy === s.id ? "Copying…" : executeLive && bridgeReady ? "↻ Copy — Live" : "↻ Copy This Signal"}
                </Btn>
              </div>
            )}
            <ConfRing val={s.confidence} size={60} />
          </div>
        </div>
        {s.approval_status === "pending_review" && (
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 8,
                        background: `${C.gold}14`, border: `1px solid ${C.gold}40`, borderRadius: 8,
                        padding: "9px 12px", marginBottom: 10, fontSize: 12 }}>
            <span>This signal hasn't been sent to your followers yet — approve it above to distribute, or reject to discard it.</span>
          </div>
        )}
        {lastCopied && lastCopied.pair === s.pair && (
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between",
                        background: `${C.green}18`, border: `1px solid ${C.green}40`, borderRadius: 8,
                        padding: "9px 12px", marginBottom: 10, fontSize: 12 }}>
            <span>✓ Placed as a copy trade{lastCopied.mode === "mt5" ? " (sent to your MT5 bridge)" : " (simulated)"} — {lastCopied.pair} {lastCopied.direction}</span>
            <NavLink to="/copy" style={{ color: C.gold, fontWeight: 700, textDecoration: "none", whiteSpace: "nowrap", marginLeft: 10 }}>
              View in Copy Trading →
            </NavLink>
          </div>
        )}
        <ErrBox msg={copyErr} />

        {/* Metric grid */}
        <Grid  cols="repeat(4,minmax(0,1fr))" mobileCols="1fr 1fr" gap={12} style={{ marginBottom: 18 }}>
          {[["ENTRY", fp(s.entry_price), C.text], ["STOP LOSS", fp(s.stop_loss), C.red], ["TAKE PROFIT", fp(s.take_profit), C.green],
            ["SL PIPS", f1(s.sl_pips), C.red], ["TP PIPS", f1(s.tp_pips), C.green], ["R:R", `1:${s.risk_reward}`, C.gold],
          ].map(([l, v, c]) => (
            <div key={l} style={{
              background: `linear-gradient(160deg, ${c}12, ${C.surf2})`,
              border: `1px solid ${C.border}`, borderTop: `2px solid ${c}`,
              borderRadius: 10, padding: "12px 10px", textAlign: "center",
            }}>
              <div style={{ fontSize: 9, color: C.muted, letterSpacing: 0.6, marginBottom: 4, fontWeight: 600 }}>{l}</div>
              <div style={{ fontSize: 15, fontWeight: 800, color: c, fontFamily: "monospace" }}>{v}</div>
            </div>
          ))}
        </Grid>

        {/* Chart */}
        <ChartWrap label="Live Chart">
          <CandleChart1
            bars={bars}
            resetKey={`${s.id}_${s.pair}_${s.timeframe}`}
            pair={s.pair}
            timeframe={s.timeframe}
            api={api}
            height={mobile ? 320 : 560}
            entry={s.entry_price} sl={s.stop_loss} tp={s.take_profit}
            markers={s.markers || []}
            supportResistance={s.support_resistance || []}
            trendline={s.trendline || null}
            liveCandle={liveCandle}
            live={selCandleStatus === "open"}
            indicators={marketPrefs.indicators}
          />
        </ChartWrap>

        {/* Indicators + AI side by side */}
        <Grid cols="1fr 1fr" gap={12}>
          <ChartWrap label="Technical Indicators">
            {[["RSI",     s.rsi,      0,   100],
              ["Stoch K", s.stoch_k,  0,   100],
              ["EMA 20",  s.ema20,    null, null],
              ["EMA 50",  s.ema50,    null, null],
              ["EMA 200", s.ema200,   null, null],
              ["BB Upper",s.bb_upper, null, null],
              ["BB Lower",s.bb_lower, null, null],
              ["ATR",     s.atr,      null, null],
            ].map(([l, v, lo, hi]) => (
              <div key={l} style={{ display: "flex", alignItems: "center", gap: 8, padding: "4px 0", borderBottom: `1px solid ${C.border}20`, fontSize: 11 }}>
                <span style={{ width: 68, color: C.muted, fontSize: 10, flexShrink: 0 }}>{l}</span>
                <span style={{ width: 72, textAlign: "right", fontFamily: "monospace", fontWeight: 600, flexShrink: 0 }}>{hi != null ? f1(v) : fp(v)}</span>
                {hi != null && (
                  <div style={{ flex: 1, height: 3, background: C.border, borderRadius: 2 }}>
                    <div style={{ width: `${Math.max(0, Math.min(100, ((v - lo) / (hi - lo)) * 100)).toFixed(0)}%`, height: "100%", background: C.gold, borderRadius: 2 }} />
                  </div>
                )}
              </div>
            ))}
          </ChartWrap>

          <ChartWrap label="AI Analysis">
            <div style={{ fontSize: 12, lineHeight: 1.75, color: C.text, opacity: 0.88, marginBottom: 13 }}>{s.ai_analysis}</div>
            <div style={{ fontSize: 9, color: C.muted, letterSpacing: 2, marginBottom: 6 }}>PATTERNS DETECTED</div>
            <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 14 }}>
              <Badge col={dc}>{s.candle_pattern}</Badge>
              <Badge col={C.blue}>{s.chart_pattern}</Badge>
            </div>
            <div style={{ border: `1px solid ${dc}40`, background: dc + "0e", borderRadius: 8, padding: 13 }}>
              <div style={{ fontSize: 9, color: dc, letterSpacing: 2, marginBottom: 7 }}>RECOMMENDATION</div>
              <div style={{ fontSize: 12, lineHeight: 1.85 }}>
                <strong>{s.direction}</strong> {s.pair} at <strong style={{ color: C.gold, fontFamily: "monospace" }}>{fp(s.entry_price)}</strong><br />
                SL: <strong style={{ color: C.red, fontFamily: "monospace" }}>{fp(s.stop_loss)}</strong> ({f1(s.sl_pips)} pips) &nbsp;
                TP: <strong style={{ color: C.green, fontFamily: "monospace" }}>{fp(s.take_profit)}</strong> ({f1(s.tp_pips)} pips)<br />
                Best time: <strong style={{ color: C.gold }}>{s.entry_time}</strong>
              </div>
            </div>
          </ChartWrap>
        </Grid>
      </Card>
    );
  };

  return (
    <div style={{ padding: 20 }}>
      {/* Sub tabs */}
      <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
        <Btn col={subTab === "gen" ? C.gold : C.muted} ghost={subTab !== "gen"} onClick={() => { setSubTab("gen"); setResSel(null); }} style={{ fontSize: 11, padding: "6px 14px" }}>⚡ Generate</Btn>
        <Btn col={subTab === "history" ? C.gold : C.muted} ghost={subTab !== "history"} onClick={() => { setSubTab("history"); setResSel(null); }} style={{ fontSize: 11, padding: "6px 14px" }}>📊 History</Btn>
        <Btn col={subTab === "backtest" ? C.gold : C.muted} ghost={subTab !== "backtest"} onClick={() => { setSubTab("backtest"); setResSel(null); }} style={{ fontSize: 11, padding: "6px 14px" }}>🧪 Backtest</Btn>
      </div>

      {pendingReview.length > 0 && (
        <div style={{ background: `${C.gold}10`, border: `1px solid ${C.gold}45`, borderRadius: 10, padding: 14, marginBottom: 16 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
            <span style={{ fontSize: 16 }}>⏳</span>
            <strong style={{ fontSize: 13 }}>Awaiting your approval ({pendingReview.length})</strong>
            <span style={{ fontSize: 11, color: C.muted }}>— your followers won't see these until you confirm each one</span>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {pendingReview.map((s) => (
              <div key={s.id} style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", background: "#0b1723", border: "1px solid #1f2937", borderRadius: 8, padding: "8px 12px" }}>
                <Badge col={s.direction === "BUY" ? C.green : C.red}>{s.direction}</Badge>
                <strong style={{ fontSize: 13 }}>{s.pair}</strong>
                <Badge col={C.muted}>{s.timeframe}</Badge>
                <span style={{ fontSize: 11, fontFamily: "monospace" }}>Entry {fp(s.entry_price)}</span>
                <span style={{ fontSize: 11, color: C.gold }}>{s.confidence}% confidence</span>
                <div style={{ marginLeft: "auto", display: "flex", gap: 6 }}>
                  <Btn col={C.red} ghost onClick={() => rejectSignal(s.id)} disabled={pendingBusy === s.id} style={{ fontSize: 11, padding: "5px 12px" }}>
                    {pendingBusy === s.id ? "…" : "✗ Reject"}
                  </Btn>
                  <Btn col={C.green} onClick={() => approveSignal(s.id)} disabled={pendingBusy === s.id} style={{ fontSize: 11, padding: "5px 12px" }}>
                    {pendingBusy === s.id ? "…" : "✓ Approve — send to followers"}
                  </Btn>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {delayInfo && delayInfo.delay > 0 && delayInfo.locked > 0 && (
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10,
                      background: `${C.gold}14`, border: `1px solid ${C.gold}40`, borderRadius: 8,
                      padding: "9px 12px", marginBottom: 14, fontSize: 12, flexWrap: "wrap" }}>
          <span>🔒 {delayInfo.locked} real-time signal{delayInfo.locked === 1 ? "" : "s"} available now — Free plan shows signals {delayInfo.delay} min delayed.</span>
          <NavLink to="/billing" style={{ color: C.gold, fontWeight: 700, textDecoration: "none", whiteSpace: "nowrap" }}>Upgrade for real-time →</NavLink>
        </div>
      )}

      {subTab === "gen" && (
        <Grid cols="290px 1fr" gap={16}>
          {/* Left controls */}
          <div>
            <Card>
              <SectionTitle>Single Signal</SectionTitle>
              <FG label="Pair"><Sel value={pair} onChange={e => setPair(e.target.value)} options={FOREX_PAIRS} /></FG>
              <FG label="Timeframe"><Sel value={tf} onChange={e => setTf(e.target.value)} options={TFS} /></FG>
              <ErrBox msg={genErr} />
              {usage && usage.limits.signals_per_day != null && (
                <div style={{ fontSize: 10, color: C.muted, marginBottom: 8 }}>
                  {usage.usage.signals_today}/{usage.limits.signals_per_day} signals used today
                </div>
              )}
              {usage && usage.limits.signals_per_day != null && usage.usage.signals_today >= usage.limits.signals_per_day ? (
                <NavLink to="/billing" style={{ textDecoration: "none" }}>
                  <Btn col={C.gold} full>Daily limit reached — Upgrade to Pro</Btn>
                </NavLink>
              ) : (
                <Btn col={C.gold} full onClick={generate} disabled={busy}>{busy ? "Generating…" : "⚡ Generate Signal"}</Btn>
              )}
            </Card>

            <Card>
              <SectionTitle>Bulk Generate</SectionTitle>
              {usage && !usage.limits.bulk_generate ? (
                <div>
                  <div style={{ fontSize: 11, color: C.muted, marginBottom: 12, lineHeight: 1.7 }}>
                    Scanning multiple pairs/timeframes at once is a Pro feature.
                  </div>
                  <NavLink to="/billing" style={{ textDecoration: "none" }}>
                    <Btn col={C.gold} full>Upgrade to Unlock Bulk Generate</Btn>
                  </NavLink>
                </div>
              ) : (
                <>
                  <div style={{ fontSize: 9, color: C.muted, letterSpacing: 1.5, marginBottom: 6 }}>PAIRS</div>
                  <div style={{ display: "flex", flexWrap: "wrap", gap: 4, marginBottom: 10 }}>
                    {FOREX_PAIRS.map(p => <Pill key={p} on={bulkP.includes(p)} onClick={() => setBulkP(prev => prev.includes(p) ? prev.filter(x => x !== p) : [...prev, p])}>{p}</Pill>)}
                  </div>
                  <div style={{ fontSize: 9, color: C.muted, letterSpacing: 1.5, marginBottom: 6 }}>TIMEFRAMES</div>
                  <div style={{ display: "flex", gap: 4, marginBottom: 10 }}>
                    {TFS.map(t => <Pill key={t} on={bulkTf.includes(t)} onClick={() => setBulkTf(prev => prev.includes(t) ? prev.filter(x => x !== t) : [...prev, t])}>{t}</Pill>)}
                  </div>
                  <FG label="Direction">
                    <div style={{ display: "flex", gap: 4 }}>
                      {["ALL","BUY","SELL"].map(d => <Pill key={d} on={dirF === d} onClick={() => setDirF(d)}>{d}</Pill>)}
                    </div>
                  </FG>
                  <FG label={`Min Confidence: ${minConf}%`}>
                    <input type="range" min={0} max={90} step={5} value={minConf} onChange={e => setMinConf(+e.target.value)}
                      style={{ width: "100%", accentColor: C.gold }} />
                  </FG>
                  <Btn col={C.gold} ghost full onClick={bulk} disabled={busy}>{busy ? "Generating…" : "Generate All"}</Btn>
                </>
              )}
            </Card>

            <div style={{ display: "flex", alignItems: "center", gap: 6, margin: "2px 0 8px", fontSize: 10, color: C.muted }}>
              <span style={{
                width: 6, height: 6, borderRadius: "50%",
                background: liveStatus === "open" ? C.green : C.muted,
                boxShadow: liveStatus === "open" ? `0 0 6px ${C.green}` : "none",
              }} />
              {liveStatus === "open" ? "Live signal feed connected" : "Reconnecting to live feed…"}
            </div>
            <div style={{ maxHeight: 450, overflowY: "auto" }}>
              {sigs.map(s => (
                <div key={s.id} style={newIds.has(s.id) ? { boxShadow: `0 0 0 1px ${C.gold}`, borderRadius: 9, animation: "newSigPulse 1.6s ease-out 2" } : undefined}>
                  <SigCard s={s} selected={sel?.id === s.id} onClick={() => setSel(s)} />
                </div>
              ))}
            </div>
            <style>{`@keyframes newSigPulse{0%{box-shadow:0 0 0 1px ${C.gold}}50%{box-shadow:0 0 14px 2px ${C.gold}}100%{box-shadow:0 0 0 1px ${C.gold}}}`}</style>
          </div>

          {/* Right: detail */}
          <Detail s={sel} />
        </Grid>
      )}

      {subTab === "history" && (
        <Card>
          <SectionTitle>Signal History</SectionTitle>
          <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 16, alignItems: "flex-end" }}>
            <div style={{ minWidth: 130 }}><FG label="Pair"><Sel value={hPair} onChange={e => setHPair(e.target.value)} options={FOREX_PAIRS} /></FG></div>
            <div style={{ minWidth: 100 }}><FG label="Timeframe"><Sel value={hTf} onChange={e => setHTf(e.target.value)} options={TFS} /></FG></div>
            <FG label="Period">
              <div style={{ display: "flex", gap: 5 }}>
                {["1M","3M","6M","1Y"].map(p => <Pill key={p} on={hPer === p} onClick={() => setHPer(p)}>{p}</Pill>)}
              </div>
            </FG>
            <Btn col={C.gold} onClick={loadHistory} disabled={hBusy}>{hBusy ? "Loading…" : "Load"}</Btn>
          </div>

          {hData && (
            <>
              <Grid cols="repeat(4,minmax(0,1fr))" gap={12} style={{ marginBottom: 16 }}>
                <Stat label="Total"      value={hData.count}                                                  color={C.blue} />
                <Stat label="BUY"        value={hData.signals?.filter(s => s.direction === "BUY").length || 0} color={C.green} />
                <Stat label="SELL"       value={hData.signals?.filter(s => s.direction === "SELL").length || 0} color={C.red} />
                <Stat label="Est. Win Rate" value={`${hData.estimated_winrate}%`}                             color={C.gold} />
              </Grid>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(230px,1fr))", gap: 10 }}>
                {[...(hData.signals || [])].reverse().map((s, i) => (
                  <div key={i} onClick={() => setResSel({
                        pair: s.pair, timeframe: s.timeframe, direction: s.direction,
                        entry: s.entry_price, sl: s.stop_loss, tp: s.take_profit,
                        confidence: s.confidence, label: String(s.generated_at || s.expires_at || "").slice(0, 16),
                      })}
                      style={{ background: C.surf2, border: `1px solid ${C.border}`, borderLeft: `3px solid ${s.direction === "BUY" ? C.green : C.red}`, borderRadius: 8, padding: 11, cursor: "pointer" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 7 }}>
                      <div style={{ display: "flex", gap: 5 }}>
                        <strong>{s.pair}</strong>
                        <Badge col={s.direction === "BUY" ? C.green : C.red}>{s.direction}</Badge>
                      </div>
                      <span style={{ color: C.gold, fontWeight: 700 }}>{s.confidence}%</span>
                    </div>
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 5, fontSize: 11 }}>
                      <div><div style={{ fontSize: 9, color: C.muted }}>ENTRY</div><span style={{ fontFamily: "monospace" }}>{fp(s.entry_price)}</span></div>
                      <div><div style={{ fontSize: 9, color: C.muted }}>SL</div><span style={{ color: C.red, fontFamily: "monospace" }}>{fp(s.stop_loss)}</span></div>
                      <div><div style={{ fontSize: 9, color: C.muted }}>TP</div><span style={{ color: C.green, fontFamily: "monospace" }}>{fp(s.take_profit)}</span></div>
                    </div>
                    <div style={{ display: "flex", gap: 5, marginTop: 7 }}>
                      <Badge col={{ STRONG: C.green, MODERATE: C.gold, WEAK: "#f97316", AVOID: C.red }[s.strength] || C.muted}>{s.strength}</Badge>
                      <Badge col={C.muted}>1:{s.risk_reward}</Badge>
                    </div>
                    <div style={{ fontSize: 9, color: C.muted, marginTop: 5 }}>{String(s.generated_at || s.expires_at || "").slice(0, 16)} · tap for chart</div>
                  </div>
                ))}
              </div>
              {resSel && <ResultDetail />}
            </>
          )}
        </Card>
      )}

      {subTab === "backtest" && (
        <Card>
          <SectionTitle>Signal Engine Backtest</SectionTitle>
          <div style={{ fontSize: 11, color: C.muted, marginBottom: 16, lineHeight: 1.6 }}>
            Walks bar-by-bar through history replaying the exact same decision logic used for live signals — not a
            separate idealized model — and checks whether each signal's real TP or SL got hit first. Run on
            simulated price data (no live market-data key configured), so treat this as a test of the strategy's
            internal consistency, not a promise of live performance.
          </div>
          <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 16, alignItems: "flex-end" }}>
            <div style={{ minWidth: 130 }}><FG label="Pair"><Sel value={btPair} onChange={e => setBtPair(e.target.value)} options={FOREX_PAIRS} /></FG></div>
            <div style={{ minWidth: 100 }}><FG label="Timeframe"><Sel value={btTf} onChange={e => setBtTf(e.target.value)} options={TFS} /></FG></div>
            <div style={{ minWidth: 110 }}>
              <FG label="Bars to test">
                <Sel value={String(btBars)} onChange={e => setBtBars(Number(e.target.value))}
                     options={[{ v: "500", l: "500 (fast)" }, { v: "1000", l: "1000" }, { v: "2000", l: "2000" }, { v: "3000", l: "3000 (slow)" }]} />
              </FG>
            </div>
            <Btn col={C.gold} onClick={loadBacktest} disabled={btBusy}>{btBusy ? "Running…" : "Run Backtest"}</Btn>
          </div>
          <ErrBox msg={btErr} />

          {btData && (
            <>
              <Grid cols="repeat(4,minmax(0,1fr))" mobileCols="repeat(2,minmax(0,1fr))" gap={12} style={{ marginBottom: 12 }}>
                <Stat label="Win Rate" value={`${btData.win_rate_pct}%`} color={btData.win_rate_pct >= 50 ? C.green : C.red} />
                <Stat label="Profit Factor" value={btData.profit_factor} color={btData.profit_factor >= 1 ? C.green : C.red} />
                <Stat label="Total Pips" value={`${btData.total_pips >= 0 ? "+" : ""}${btData.total_pips}`} color={btData.total_pips >= 0 ? C.green : C.red} />
                <Stat label="Max Drawdown" value={`${btData.max_drawdown_pips}p`} color={C.gold} />
              </Grid>
              <Grid cols="repeat(4,minmax(0,1fr))" mobileCols="repeat(2,minmax(0,1fr))" gap={12} style={{ marginBottom: 16 }}>
                <Stat label="Signals Fired" value={btData.total_signals_fired} color={C.blue} />
                <Stat label="Wins / Losses" value={`${btData.wins} / ${btData.losses}`} color={C.muted} />
                <Stat label="Avg Win / Loss" value={`+${btData.avg_win_pips}p / ${btData.avg_loss_pips}p`} color={C.muted} />
                <Stat label="Max Losing Streak" value={btData.max_consecutive_losses} color={C.muted} />
              </Grid>

              <div style={{ fontSize: 11, color: C.muted, marginBottom: 10, background: `${C.gold}14`, border: `1px solid ${C.gold}40`, borderRadius: 8, padding: 10 }}>
                {btData.note}
              </div>

              <div style={{ fontSize: 11, fontWeight: 700, color: C.muted, marginBottom: 8 }}>TRADE LOG (most recent {btData.trades?.length || 0})</div>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(220px,1fr))", gap: 8, maxHeight: 420, overflowY: "auto" }}>
                {[...(btData.trades || [])].reverse().map((t, i) => (
                  <div key={i} onClick={() => setResSel({
                        pair: t.pair || btData.pair, timeframe: t.timeframe || btData.timeframe, direction: t.direction,
                        entry: t.entry, sl: t.sl, tp: t.tp, confidence: t.confidence,
                        label: `${t.result.toUpperCase()} · ${String(t.entry_time).slice(0, 16)}`,
                      })}
                      style={{ background: C.surf2, border: `1px solid ${C.border}`,
                                          borderLeft: `3px solid ${t.result === "win" ? C.green : t.result === "loss" ? C.red : C.gold}`,
                                          borderRadius: 8, padding: 10, fontSize: 11, cursor: "pointer" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 5 }}>
                      <Badge col={t.direction === "BUY" ? C.green : C.red}>{t.direction}</Badge>
                      <Badge col={t.result === "win" ? C.green : t.result === "loss" ? C.red : C.muted}>{t.result.toUpperCase()}</Badge>
                    </div>
                    <div style={{ color: C.muted }}>Entry {fp(t.entry)} → Exit {fp(t.exit)}</div>
                    <div style={{ fontWeight: 700, color: t.pips >= 0 ? C.green : C.red, marginTop: 3 }}>{t.pips >= 0 ? "+" : ""}{t.pips} pips</div>
                    <div style={{ fontSize: 9, color: C.muted, marginTop: 3 }}>{String(t.entry_time).slice(0, 16)} · {t.confidence}% conf · tap for chart</div>
                  </div>
                ))}
              </div>
              {resSel && <ResultDetail />}
            </>
          )}
        </Card>
      )}
    </div>
  );
}