// ─── User Guide ───────────────────────────────────────────────────────────────
// A dedicated, in-app reference for how ForexPro actually works — every claim
// here matches real backend/frontend behavior (approval flows, fee models,
// what the wallet is and isn't, etc.), not generic placeholder help text.
import { useMemo, useState } from "react";
import { C } from "../utils/constants.jsx";
import { Card, SectionTitle, useMobile } from "../shared/Shared.jsx";
import { Icon } from "../components/Icons.jsx";

const SECTIONS = [
  {
    id: "start",
    icon: "dashboard",
    title: "Getting started",
    body: [
      "Create an account, then check your inbox and verify your email — a banner in Settings will remind you until you do.",
      "New accounts pay a one-time registration fee (M-Pesa or card) before the rest of the platform unlocks — you'll see a gold banner under the top bar until it's paid. Handle it from Billing.",
      "Your dashboard watchlist starts with a default set of pairs. Add or remove pairs any time with \"+ Add pairs\" on the Dashboard or Live Prices — it's synced to your account, so it's the same on every device you log into.",
    ],
  },
  {
    id: "dashboard",
    icon: "dashboard",
    title: "Dashboard",
    body: [
      "Your account balance and equity lead the page — equity includes floating profit/loss on anything currently open.",
      "Live Prices shows your watchlist with real-time price updates. Tap \"Defaults\" to set the timeframe and indicators every chart opens with, on Live Prices and Signals alike.",
      "Latest Signals, Active Copy Trades, and Notifications give you a quick read on anything that needs attention without leaving the page — tap any row to jump to the full page for it.",
    ],
  },
  {
    id: "prices",
    icon: "prices",
    title: "Live Prices & charting",
    body: [
      "Tap the pair or timeframe chip above the chart to open a picker — search by typing, or scroll the list.",
      "Toggle indicator overlays (EMA, Bollinger Bands, support/resistance, trendlines, volume) from the chart's own controls.",
      "Click an open trade's line on the chart to reveal its Take Profit and Stop Loss lines — drag either one directly on the chart to adjust it.",
      "The drawing toolbar (bottom-left of the chart) lets you sketch trendlines, rectangles, and horizontal levels of your own — these save per pair and timeframe, so they're there next time you come back.",
      "All chart timestamps are shown in East Africa Time (EAT), regardless of where the underlying price data comes from.",
    ],
  },
  {
    id: "signals",
    icon: "signals",
    title: "Signals",
    body: [
      "Generate a single signal for one pair/timeframe, or use Bulk Generate to scan several pairs at once.",
      "Each signal shows a confidence score, entry price, stop loss, and take profit — generated by the same engine whether you're looking at one pair or running a bulk scan.",
      "Signal Engine Backtest replays the exact decision logic used for live signals, bar-by-bar through history, and reports win rate, profit factor, drawdown, and streaks. It's a check of the strategy's internal consistency on the data available — not a guarantee of future results.",
    ],
  },
  {
    id: "copy",
    icon: "copy",
    title: "Copy Trading",
    body: [
      "Subscribe to a provider from the Providers page, choosing Auto or Manual mode.",
      "Auto mode opens a copy the moment the provider's signal fires. Manual mode holds it under \"Awaiting Your Approval\" on the Copy Trading page until you approve or decline it — nothing opens without your say-so.",
      "Providers charge either a flat monthly subscription or a commission on profitable trades only (nothing charged on a loss) — check a provider's profile before subscribing to see which.",
      "Edit a subscription's risk settings, or unsubscribe entirely, from Active Subscriptions on the Copy Trading page.",
    ],
  },
  {
    id: "providers",
    icon: "providers",
    title: "Becoming a provider",
    body: [
      "Register a provider profile from the Providers page: display name, description, trading style/risk notes, and which pairs and timeframes you actually trade.",
      "Choose your revenue model when you register — a flat monthly fee, or a percentage of follower profit per winning trade. Commission-based earnings are tracked and settled from the follower's wallet balance, since the platform doesn't have withdrawal access to anyone's broker account.",
      "Your provider dashboard shows followers, trades copied, and earnings per follower at a glance.",
    ],
  },
  {
    id: "wallet",
    icon: "billing",
    title: "Wallet vs. your broker account",
    body: [
      "The in-app wallet funds simulated copy trades — including bookkeeping for trades executed via the MT5 bridge, where margin is reserved/released here even though the real fill happens on your broker account.",
      "The wallet is not the same as money in your MT5 broker account (Exness, FBS, XM, etc.) — that's managed and withdrawn through your broker directly, not through this app.",
      "Deposit or request a withdrawal from Billing → Wallet. Withdrawals are reserved immediately but paid out manually to M-Pesa — not instant.",
    ],
  },
  {
    id: "mt5",
    icon: "profile",
    title: "Connecting MT5",
    body: [
      "On Profile, saving your broker/login/server is reference info only — it doesn't connect anything by itself.",
      "To actually let the platform place real trades, set up the MT5 Auto-Trading Bridge (Beta) card on Profile — that runs a small Expert Advisor (EA) in your own MetaTrader 5 terminal, and is the part that does the real connecting.",
      "For small accounts, an MT5 cent account (e.g. FBS Cent) lets you trade nano lots with a $1–$10 minimum deposit, useful for testing the bridge without risking much.",
    ],
  },
  {
    id: "journal",
    icon: "journal",
    title: "Journal",
    body: [
      "Every closed trade — manual or copied — lands in your Journal automatically, with entry/exit price, P&L in both dollars and pips, and what it was copied from.",
      "Use it to review what's actually working over time rather than relying on memory.",
    ],
  },
  {
    id: "education",
    icon: "education",
    title: "Education",
    body: [
      "Structured courses covering forex fundamentals through to strategy — progress is tracked per account, and completed-course count shows on your Dashboard.",
    ],
  },
  {
    id: "billing",
    icon: "billing",
    title: "Billing & plans",
    body: [
      "The one-time registration fee unlocks the platform after signup. Separately, monthly subscription plans unlock higher usage limits (signal generation, bulk scans, etc.) — both payable by M-Pesa STK push or card.",
      "Your current plan and usage against its limits are shown at the top of the Billing page.",
    ],
  },
  {
    id: "notifications",
    icon: "bell",
    title: "Notifications & alerts",
    body: [
      "In-app notifications (the bell icon) cover trade closes, copy-signal activity, and account events, and stay on by default.",
      "Email alerts for the same events can be turned off in Settings if you only want the in-app ones.",
      "Connect Telegram from Settings to also get a message the moment a provider you follow posts a new signal — on top of the in-app notification, not instead of it.",
    ],
  },
  {
    id: "settings",
    icon: "settings",
    title: "Settings",
    body: [
      "Appearance: choose Auto (follows your device), Dark, Pure Black, or Light — Auto keeps watching your system setting and switches live if it changes.",
      "Dashboard modules: toggle optional widgets like the market news feed on or off — saved on this device.",
      "Default lot size and risk % are the starting point pre-filled when you manually copy a signal — you can still adjust per trade.",
    ],
  },
];

function AccordionItem({ section, isOpen, onToggle }) {
  return (
    <div style={{ borderBottom: `1px solid ${C.border}` }}>
      <button
        onClick={onToggle}
        style={{
          width: "100%", display: "flex", alignItems: "center", gap: 12,
          padding: "13px 4px", background: "none", border: "none", cursor: "pointer",
          textAlign: "left", color: C.text, fontFamily: "inherit",
        }}
      >
        <div style={{
          width: 30, height: 30, borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center",
          background: isOpen ? `${C.gold}18` : C.surf2, color: isOpen ? C.gold : C.muted, flexShrink: 0,
        }}>
          <Icon name={section.icon} size={15} />
        </div>
        <span style={{ flex: 1, fontSize: 13, fontWeight: 700 }}>{section.title}</span>
        <Icon name="chevronDown" size={14} style={{ color: C.muted, transform: isOpen ? "rotate(180deg)" : "none", transition: "transform .15s" }} />
      </button>
      {isOpen && (
        <div style={{ padding: "0 4px 16px 46px", display: "flex", flexDirection: "column", gap: 9 }}>
          {section.body.map((p, i) => (
            <div key={i} style={{ fontSize: 12, lineHeight: 1.65, color: C.muted }}>{p}</div>
          ))}
        </div>
      )}
    </div>
  );
}

export default function UserGuide() {
  const mobile = useMobile();
  const [openId, setOpenId] = useState("start");
  const [query, setQuery] = useState("");

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return SECTIONS;
    return SECTIONS.filter((s) =>
      s.title.toLowerCase().includes(q) || s.body.some((p) => p.toLowerCase().includes(q))
    );
  }, [query]);

  return (
    <div style={{ padding: mobile ? 12 : 20, marginBottom: 100, maxWidth: 720, margin: "0 auto" }}>
      <SectionTitle>User Guide</SectionTitle>
      <div style={{ fontSize: 12, color: C.muted, marginBottom: 14, marginTop: -6 }}>
        How ForexPro's features actually work, in plain terms.
      </div>

      <div style={{ position: "relative", marginBottom: 14 }}>
        <span style={{ position: "absolute", left: 12, top: "50%", transform: "translateY(-50%)", color: C.muted }}>
          <Icon name="search" size={14} />
        </span>
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder='Search the guide — e.g. "wallet", "approval", "theme"…'
          style={{
            width: "100%", padding: "10px 12px 10px 34px", background: C.surf2,
            border: `1px solid ${C.border}`, borderRadius: 8, color: C.text, fontSize: 12.5,
            boxSizing: "border-box",
          }}
        />
      </div>

      <Card style={{ padding: "4px 14px" }}>
        {filtered.length === 0 ? (
          <div style={{ padding: "20px 4px", color: C.muted, fontSize: 12, textAlign: "center" }}>
            No sections match "{query}".
          </div>
        ) : (
          filtered.map((section) => (
            <AccordionItem
              key={section.id}
              section={section}
              isOpen={openId === section.id}
              onToggle={() => setOpenId((cur) => (cur === section.id ? null : section.id))}
            />
          ))
        )}
      </Card>
    </div>
  );
}
